### ISSUE TITLE
Font color not being applied to word definition (CSS)

### ISSUE THREAD

**Issue by LedaThemis** [pnlpal/dictionariez#80]
![image](https://user-images.githubusercontent.com/38331868/164133770-d755cccb-9581-4be8-bbb7-bda952edfd4e.png)
![image](https://user-images.githubusercontent.com/38331868/164133752-9cbe1d5b-61d7-42fb-9acd-7fd1dcdb9c32.png)

As you can see from the screenshots, `color` is being overwritten by a another style rule from the website (which is in this case [libredd.it](https://libredd.it/)) 

this is due to the fact that "styles for a directly targeted element will always take precedence over inherited styles" (read more on [Directly targeted elements vs. inherited styles | MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity#directly_targeted_elements_vs._inherited_styles))

This can be fixed by adding `.fairydict-content, .fairydict-prons` to:
```css
.dictionaries-tooltip .dictionaries-tooltip-content, .fairydict-content, .fairydict-prons {
  color: #fff;
  font-size: 14px;
  line-height: normal;
}
```
or perhaps `.fairydict-symbol, .fairydict-pos, .fairydict-def` would be more consistent?

*as for the play audio icons, I'll report them in the next issue*
